services:
  api:
    image: "johnb340/moby-dick-rag-fusion:v1"
    hostname: api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  streamlit:
    image: "johnb340/moby-dick-streamlit:v3"
    ports:
      - "8501:8501"